### ISSUE TITLE
This package seems to have bitrotted a little bit

### ISSUE THREAD

**Issue by expipiplus1** [lspitzner/iridium#5]
It's really useful! It's the only reason I still have a 7.10 compiler on my machine!

**Comment by lspitzner** [comment]
Right. I have just pushed some fixes that have accumulated over here. I think they un-break things. Please tell if i have missed something.

There is also the topic of supporting new-build (by now, iridium is not only is this why have 7.10 on my machine, too, but also why i still use sandboxes :-)

57faa6af16d5eb67217e4e29c392da6090c292d0 has some start in this direction. It expects cabal project files like `cabal.project.ghc-8.0.2`. But this feature is completely unfinished and untested. (supporting stack is also feasible and probably trivial, because it seems to be rather parallel to new-build.)

Any comments about the new-build support design? Is different `cabal.project.ghc-x.x.x` files fine?

(and there is one more to-do on my list: i think half of this project's dependency footprint comes from my rather stupid mistake of not making use of hackage's json endpoint.)

**Comment by expipiplus1** [comment]
no ideas here I'm afraid, I'm still using cabal old-build with nix.
